import type { Child, FamilyEvent, SchoolHoliday } from "./types";

export const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export const hours = Array.from({ length: 14 }, (_, i) => i + 7); // 7:00 -> 20:00

export const children: Child[] = [
  { name: "Juliette", level: "Grade 3" },
  { name: "Chloe", level: "Kindy" },
];

export const events: FamilyEvent[] = [
  {
    id: "juliette-school-mon",
    title: "School",
    child: "Juliette",
    day: "Mon",
    startMinutes: 525,
    endMinutes: 930,
    category: "school",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "juliette-school-tue",
    title: "School",
    child: "Juliette",
    day: "Tue",
    startMinutes: 525,
    endMinutes: 930,
    category: "school",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "juliette-school-wed",
    title: "School",
    child: "Juliette",
    day: "Wed",
    startMinutes: 525,
    endMinutes: 930,
    category: "school",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "juliette-school-thu",
    title: "School",
    child: "Juliette",
    day: "Thu",
    startMinutes: 525,
    endMinutes: 930,
    category: "school",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "juliette-school-fri",
    title: "School",
    child: "Juliette",
    day: "Fri",
    startMinutes: 525,
    endMinutes: 930,
    category: "school",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "chloe-kindy-mon",
    title: "Kindy",
    child: "Chloe",
    day: "Mon",
    startMinutes: 540,
    endMinutes: 840,
    category: "kindy",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "chloe-kindy-wed",
    title: "Kindy",
    child: "Chloe",
    day: "Wed",
    startMinutes: 540,
    endMinutes: 840,
    category: "kindy",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "chloe-kindy-fri",
    title: "Kindy",
    child: "Chloe",
    day: "Fri",
    startMinutes: 540,
    endMinutes: 840,
    category: "kindy",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "juliette-homework-mon",
    title: "Homework",
    child: "Juliette",
    day: "Mon",
    startMinutes: 1020,
    endMinutes: 1050,
    category: "homework",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "juliette-homework-tue",
    title: "Homework",
    child: "Juliette",
    day: "Tue",
    startMinutes: 1020,
    endMinutes: 1050,
    category: "homework",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "juliette-homework-wed",
    title: "Homework",
    child: "Juliette",
    day: "Wed",
    startMinutes: 1020,
    endMinutes: 1050,
    category: "homework",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "juliette-homework-thu",
    title: "Homework",
    child: "Juliette",
    day: "Thu",
    startMinutes: 1020,
    endMinutes: 1050,
    category: "homework",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: false,
  },
  {
    id: "family-dinner-mon",
    title: "Dinner",
    child: "Family",
    day: "Mon",
    startMinutes: 1110,
    endMinutes: 1140,
    category: "family",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: true,
    alwaysActive: true,
  },
  {
    id: "family-dinner-tue",
    title: "Dinner",
    child: "Family",
    day: "Tue",
    startMinutes: 1110,
    endMinutes: 1140,
    category: "family",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: true,
    alwaysActive: true,
  },
  {
    id: "family-dinner-wed",
    title: "Dinner",
    child: "Family",
    day: "Wed",
    startMinutes: 1110,
    endMinutes: 1140,
    category: "family",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: true,
    alwaysActive: true,
  },
  {
    id: "family-dinner-thu",
    title: "Dinner",
    child: "Family",
    day: "Thu",
    startMinutes: 1110,
    endMinutes: 1140,
    category: "family",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: true,
    alwaysActive: true,
  },
  {
    id: "family-dinner-fri",
    title: "Dinner",
    child: "Family",
    day: "Fri",
    startMinutes: 1110,
    endMinutes: 1140,
    category: "family",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: true,
    alwaysActive: true,
  },
  {
    id: "family-dinner-sat",
    title: "Dinner",
    child: "Family",
    day: "Sat",
    startMinutes: 1110,
    endMinutes: 1140,
    category: "family",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: true,
    alwaysActive: true,
  },
  {
    id: "family-dinner-sun",
    title: "Dinner",
    child: "Family",
    day: "Sun",
    startMinutes: 1110,
    endMinutes: 1140,
    category: "family",
    appliesDuringSchoolWeeks: true,
    appliesDuringHolidays: true,
    alwaysActive: true,
  },
];

export const schoolHolidays: SchoolHoliday[] = [
  {
    id: "vic-2026-autumn",
    name: "Autumn school holidays",
    state: "VIC",
    startDate: "2026-04-03",
    endDate: "2026-04-17",
  },
  {
    id: "vic-2026-winter",
    name: "Winter school holidays",
    state: "VIC",
    startDate: "2026-06-27",
    endDate: "2026-07-12",
  },
  {
    id: "vic-2026-spring",
    name: "Spring school holidays",
    state: "VIC",
    startDate: "2026-09-19",
    endDate: "2026-10-04",
  },
  {
    id: "vic-2026-summer",
    name: "Summer school holidays",
    state: "VIC",
    startDate: "2026-12-19",
    endDate: "2027-01-26",
  },
];
